export * as BackEnd        from "./BackEnd";
export * as C              from "./C";
export * as CapacitorJs    from "./CapacitorJs";
export * as CSharp         from "./CSharp";
export * as Css            from "./Css";
export * as FrontEnd       from "./FrontEnd";
export * as GitHub         from "./GitHub";
export * as Gmail          from "./Gmail";
export * as HTML           from "./HTML";
export * as Js             from "./Js";
export * as MobileTablette from "./MobileTablette";
export * as NodeJs         from "./NodeJs";
export * as Python         from "./Python";
export * as ReactJs        from "./ReactJs";
export * as Sass           from "./Sass";
export * as Ts             from "./Ts";
export * as VueJs          from "./VueJs"
export * as Webpack        from "./Webpack";
