export const aboutMe_1_EN : string = "I am a <b>software engineer with 5 years of experience</b> in the field. My expertise lies in <b>full-stack web development</b>, where I enjoy using my skills in both front-end and back-end technologies to <b>create dynamic and user-friendly applications</b>. I am a <b>dedicated learner</b> and am constantly seeking to expand my knowledge and skills.";

export const aboutMe_1_FR : string = "Je suis un <b>ingénieur logiciel avec 5 ans d'expérience</b> dans le domaine. Mon expertise réside dans le <b>développement web full-stack</b>, où j'aime utiliser mes compétences dans les technologies front-end et back-end pour <b>créer des applications dynamiques et facile à utiliser</b>. J'<b>aime apprendre</b> et je cherche constamment à élargir mes connaissances et compétences.";

export const aboutMe_2_EN : string = "For example, one area of software engineering that I am particularly passionate about is the development of <b>graphical software</b>. I enjoy the challenge of creating visually <b>appealing and intuitive interfaces</b> that make it easy for users to interact with the underlying data and logic.";

export const aboutMe_2_FR : string = "Par exemple, un domaine de l'ingénierie logicielle qui me passionne particulièrement est le développement de <b>logiciels graphiques</b>. J'aime le défi de créer des <b>interfaces visuellement attrayantes et intuitives</b> qui facilitent l'interaction des utilisateurs avec les données et la logique sous-jacentes.";

export const aboutMe_3_EN : string = "I am confident in my ability to provide <b>high-quality solutions</b> to meet the needs of any client and I am always eager to take on new challenges. <b>I look forward to the opportunity to work with you</b>.";

export const aboutMe_3_FR : string = "Je suis confiant dans ma capacité à fournir des <b>solutions de haute qualité</b> pour répondre aux besoins de tous les clients et je suis toujours enthousiaste à l'idée de relever de nouveaux défis. <b>J'ai hâte de pouvoir travailler avec vous</b>.";

export const propositionFrontEnd_EN : string = "Skilled front-end developer with expertise in <b>TypeScript</b>, <b>HTML</b>, and <b>CSS/SASS</b>. Proficient in <b>React</b> and <b>Vue.js</b> frameworks, with a focus on React. I Build responsive and user-friendly web applications with a keen eye for detail and a deep understanding of user experience. Passionate about creating high-quality web experiences.";

export const propositionFrontEnd_FR : string = "Développeur front-end expérimenté avec une expertise en <b>TypeScript</b>, <b>HTML</b> et <b>CSS/SASS</b>. Compétences avancées dans les frameworks <b>React</b> et <b>Vue.js</b>, avec une spécialisation sur React. Crée des applications web réactives et axées sur l'utilisateur, avec un souci du détail et une compréhension approfondie de l'expérience utilisateur. Passionné par la création d'expériences web de qualité supérieure.";

export const propositionBackEnd_EN : string = "Skilled back-end engineer with expertise in <b>Node.js</b>, <b>Express</b>, and REST API design. Adaptable to new network protocols and experienced in setting up, and requesting data from, <b>SQL/NoSQL</b> databases (<b>SQLite</b>, <b>MongoDB</b>, <b>PostGres</b>, etc) or serverless architectures (Firebase, etc). Passionate about building scalable and reliable back-end systems.";

export const propositionBackEnd_FR : string = "Ingénieur back-end expérimenté avec une expertise en <b>Node.js</b>, <b>Express</b> et la conception d'API REST. Adaptable aux nouveaux protocoles de réseau et expérimenté dans la configuration et la récupération de données à partir de bases de données <b>SQL/NoSQL</b> (<b>SQLite</b>, <b>MongoDB</b>, <b>PostGres</b>, etc) ou des architectures serverless (Firebase, etc). Passionné par la construction de systèmes back-end évolutifs et fiables.";

export const propositionMobile_EN : string = "Mobile app developer with experience in <b>React Native</b> and <b>Capacitor</b> for building mobile apps with React code, maintaining a single code base for web and mobile apps. Committed to building user-friendly and performant mobile apps.";

export const propositionMobile_FR : string = "Développeur d'applications mobiles avec de l'expérience en <b>React Native</b> et <b>Capacitor</b> pour la création d'applications mobiles avec du code React, en maintenant une base de code unique pour les applications web et mobiles. Dédié à la création d'applications mobiles conviviales et performantes.";

export const projectGraphCollapse_EN : string = "This is a small graphics project demonstrating my ability to work with the HTMLCanvas, graph structures, and graph algorithms. This project combines some simple combinatorics and motion physics in the code. I have also worked with directed graph NoSQL databases.";

export const projectGraphCollapse_FR : string = "Ceci est un petit projet de graphisme démontrant ma capacité à travailler avec HTMLCanvas, les structures de graphs et les algorithmes de graphs. Ce projet combine une combinatoire simple et une physique de mouvement. J'ai également travaillé avec des bases de données NoSQL de graphs orientés."

export const projectRasterizer_EN : string = "This is a rasterizer project that runs on the CPU, displaying 3D models from OBJ files at 30 frames per second. This project utilizes an HTMLCanvas and a custom CGI pipeline, all built from scratch. It showcases that I have a decent understanding of CGI and linear algebra. I produced this web applet in order to learn linear algebra because I was interested in learning about AI and ML.";

export const projectRasterizer_FR : string = "Il s'agit d'un projet de rasterisation fonctionnant qui tourne sur le CPU, qui affiche des modèles 3D à partir de fichiers OBJ à 30 images par seconde. Ce projet utilise un HTMLCanvas et un pipeline CGI créer à partir de zéro. Il démontre que j'ai une bonne compréhension de la CGI et de l'algèbre linéaire. J'ai produit cette application web afin d'apprendre l'algèbre linéaire, car j'étais intéressé par l'apprentissage de l'IA et de la ML."

export const tutorial_EN : string = "To open the panel with the list of action keybindings, you can either click and hold the mouse button on the keyboard icon, or press and hold the Alt key on your keyboard.";

export const tutorial_FR : string = "Pour ouvrir le panneau affichant la liste des raccourcis clavier, vous pouvez soit cliquer et maintenir le bouton de la souris sur l'icône du clavier, soit appuyer et maintenir enfoncée la touche Alt de votre clavier.";

export const projectAnimatedCube_EN : string = "This animated cube, crafted solely with HTML and CSS, demonstrates my proficiency and deep understanding of foundational web technologies. Through meticulous structuring and CSS styling, I showcase my ability to create engaging, visually appealing elements with smooth animations and transitions - even with limited tools, and without the need to rely on external libraries or frameworks. Since I can manage to produce quality work, even with such constraints, I believe that this project serves as a good example of my long-term commitment to truly mastering the fundamentals of web development.";

export const projectAnimatedCube_FR : string = "Ce cube animé, conçu uniquement avec du HTML et du CSS, démontre mon expertise et ma compréhension approfondie des technologies web fondamentales. Grâce à une structuration minutieuse et à un style CSS, je mets en avant ma capacité à créer des éléments attrayants visuellement et avec des animations et transitions fluides, même avec des outils limités et sans avoir besoin de recourir à des bibliothèques ou des frameworks externes. Puisque je peux produire un travail de qualité, même dans de telles contraintes, je crois que ce projet sert d'exemple de mon engagement à long terme à maîtriser véritablement les fondamentaux du développement web.";
