export const aboutMe_1 : string = "I am a software engineer with 5 years of experience in the field. My expertise lies in full-stack web development, where I enjoy using my skills in both front-end and back-end technologies to create dynamic and user-friendly applications. I am a dedicated learner and am constantly seeking to expand my knowledge and skills. One area of software engineering that I am particularly passionate about is the development of graphical software. I enjoy the challenge of creating visually appealing and intuitive interfaces that make it easy for users to interact with the underlying data and logic.";

export const aboutMe_2 : string = "I am confident in my ability to provide high-quality solutions to meet the needs of any client and I am always eager to take on new challenges. Thank you for considering my portfolio. I look forward to the opportunity to work with you.";

export const propositionFrontEnd : string = "Skilled front-end developer with expertise in <b>TypeScript</b>, <b>HTML</b>, and <b>CSS/SASS</b>. Proficient in <b>React</b> and <b>Vue.js</b> frameworks, with a focus on React. Builds responsive and user-friendly web applications with a keen eye for detail and a deep understanding of user experience. Passionate about creating high-quality web experiences.";

export const propositionBackEnd : string = "Skilled back-end engineer with expertise in <b>Node.js</b>, <b>Express</b>, and REST API design. Adaptable to new network protocols and experienced in setting up, and requesting data from, <b>SQL/NoSQL</b> databases (<b>SQLite</b>, <b>MongoDB</b>, <b>PostGres</b>, etc) or serverless architectures (Firebase, etc). Passionate about building scalable and reliable back-end systems.";

export const propositionMobile : string = "Mobile app developer with experience in <b>React Native</b> and <b>Capacitor</b> for building mobile apps with React code, maintaining a single code base for web and mobile apps. Committed to building user-friendly and performant mobile apps.";

export const projectGraphCollapse : string = "This is a small graphics project demonstrating my ability to work with the HTMLCanvas, graph structures, and graph algorithms. This project combines some simple combinatorics and motion physics in the code. I have also worked with directed graph NoSQL databases (not Neo4j, though).";

export const projectRasterizer : string = "This is a rasterizer project that runs on the CPU, displaying 3D models from OBJ files at 30 frames per second. This project utilizes an HTMLCanvas and a custom CGI pipeline, all built from scratch. It showcases that I have a decent understanding of CGI and linear algebra. I produced this web applet in order to learn linear algebra because I was interested in learning about AI and ML.";

export const projectAnimatedCube : string = "The animated cube, crafted solely with HTML and CSS, demonstrates my proficiency and deep understanding of these foundational web technologies. Through meticulous structure and CSS styling, I showcase my ability to create engaging, visually appealing elements with smooth animations and transitions. This project reflects my commitment to staying current with web trends, as I leverage core technologies rather than relying on external libraries or frameworks. This accomplishment highlights my dedication, creativity, and passion for web development within a concise, self-contained creation.";
