export const aboutMe_1_EN : string = "I am a software engineer with 5 years of experience in the field. My expertise lies in full-stack web development, where I enjoy using my skills in both front-end and back-end technologies to create dynamic and user-friendly applications. I am a dedicated learner and am constantly seeking to expand my knowledge and skills. One area of software engineering that I am particularly passionate about is the development of graphical software. I enjoy the challenge of creating visually appealing and intuitive interfaces that make it easy for users to interact with the underlying data and logic.";

export const aboutMe_1_FR : string = "Je suis un ingénieur logiciel avec 5 ans d'expérience dans le domaine. Mon expertise réside dans le développement web full-stack, où j'aime utiliser mes compétences dans les technologies front-end et back-end pour créer des applications dynamiques et facile à utiliser. J'aime apprendre et je cherche constamment à élargir mes connaissances et compétences. Un domaine de l'ingénierie logicielle qui me passionne particulièrement est le développement de logiciels graphiques. J'aime le défi de créer des interfaces visuellement attrayantes et intuitives qui facilitent l'interaction des utilisateurs avec les données et la logique sous-jacentes.";

export const aboutMe_2_EN : string = "I am confident in my ability to provide high-quality solutions to meet the needs of any client and I am always eager to take on new challenges. Thank you for considering my portfolio. I look forward to the opportunity to work with you.";

export const aboutMe_2_FR : string = "Je suis confiant dans ma capacité à fournir des solutions de haute qualité pour répondre aux besoins de tous les clients et je suis toujours enthousiaste à l'idée de relever de nouveaux défis. Je vous remercie de considérer mon portfolio. J'ai hâte de pouvoir travailler avec vous.";

export const propositionFrontEnd_EN : string = "Skilled front-end developer with expertise in <b>TypeScript</b>, <b>HTML</b>, and <b>CSS/SASS</b>. Proficient in <b>React</b> and <b>Vue.js</b> frameworks, with a focus on React. Builds responsive and user-friendly web applications with a keen eye for detail and a deep understanding of user experience. Passionate about creating high-quality web experiences.";

export const propositionFrontEnd_FR : string = "Développeur front-end expérimenté avec une expertise en <b>TypeScript</b>, <b>HTML</b> et <b>CSS/SASS</b>. Compétences avancées dans les frameworks <b>React</b> et <b>Vue.js</b>, avec une spécialisation sur React. Crée des applications web réactives et axées sur l'utilisateur, avec un souci du détail et une compréhension approfondie de l'expérience utilisateur. Passionné par la création d'expériences web de qualité supérieure.";

export const propositionBackEnd_EN : string = "Skilled back-end engineer with expertise in <b>Node.js</b>, <b>Express</b>, and REST API design. Adaptable to new network protocols and experienced in setting up, and requesting data from, <b>SQL/NoSQL</b> databases (<b>SQLite</b>, <b>MongoDB</b>, <b>PostGres</b>, etc) or serverless architectures (Firebase, etc). Passionate about building scalable and reliable back-end systems.";

export const propositionBackEnd_FR : string = "Ingénieur back-end expérimenté avec une expertise en <b>Node.js</b>, <b>Express</b> et la conception d'API REST. Adaptable aux nouveaux protocoles de réseau et expérimenté dans la configuration et la récupération de données à partir de bases de données <b>SQL/NoSQL</b> (<b>SQLite</b>, <b>MongoDB</b>, <b>PostGres</b>, etc) ou des architectures serverless (Firebase, etc). Passionné par la construction de systèmes back-end évolutifs et fiables.";

export const propositionMobile_EN : string = "Mobile app developer with experience in <b>React Native</b> and <b>Capacitor</b> for building mobile apps with React code, maintaining a single code base for web and mobile apps. Committed to building user-friendly and performant mobile apps.";

export const propositionMobile_FR : string = "Développeur d'applications mobiles avec de l'expérience en <b>React Native</b> et <b>Capacitor</b> pour la création d'applications mobiles avec du code React, en maintenant une base de code unique pour les applications web et mobiles. Dédié à la création d'applications mobiles conviviales et performantes.";

export const projectGraphCollapse_EN : string = "This is a small graphics project demonstrating my ability to work with the HTMLCanvas, graph structures, and graph algorithms. This project combines some simple combinatorics and motion physics in the code. I have also worked with directed graph NoSQL databases (not Neo4j, though).";

export const projectGraphCollapse_FR : string = "Ceci est un petit projet de graphisme démontrant ma capacité à travailler avec HTMLCanvas, les structures de graphs et les algorithmes de graphs. Ce projet combine une combinatoire simple et une physique de mouvement. J'ai également travaillé avec des bases de données NoSQL de graphs orientés (autre que Neo4j)."

export const projectRasterizer_EN : string = "This is a rasterizer project that runs on the CPU, displaying 3D models from OBJ files at 30 frames per second. This project utilizes an HTMLCanvas and a custom CGI pipeline, all built from scratch. It showcases that I have a decent understanding of CGI and linear algebra. I produced this web applet in order to learn linear algebra because I was interested in learning about AI and ML.";

export const projectRasterizer_FR : string = "Il s'agit d'un projet de rasterisation fonctionnant qui tourne sur le CPU, qui affiche des modèles 3D à partir de fichiers OBJ à 30 images par seconde. Ce projet utilise un HTMLCanvas et un pipeline CGI créer à partir de zéro. Il démontre que j'ai une bonne compréhension de la CGI et de l'algèbre linéaire. J'ai produit cette application web afin d'apprendre l'algèbre linéaire, car j'étais intéressé par l'apprentissage de l'IA et de la ML."

export const projectAnimatedCube_EN : string = "The animated cube, crafted solely with HTML and CSS, demonstrates my proficiency and deep understanding of these foundational web technologies. Through meticulous structure and CSS styling, I showcase my ability to create engaging, visually appealing elements with smooth animations and transitions. This project reflects my commitment to staying current with web trends, as I leverage core technologies rather than relying on external libraries or frameworks. This accomplishment highlights my dedication, creativity, and passion for web development within a concise, self-contained creation.";

export const projectAnimatedCube_FR : string = "Le cube animé, entièrement réalisé avec du HTML et du CSS, démontre mes compétences et ma compréhension approfondie de ces technologies web fondamentales. Grâce à une structure soignée et à un style CSS, je démontre ma capacité à créer des éléments attrayants et engageants avec des animations et des transitions fluides. Ce projet reflète mon engagement à me tenir au courant des tendances web, car j'utilise les technologies de base plutôt que de m'appuyer uniquement sur des bibliothèques externes. Cet accomplissement met en évidence mon dévouement, ma créativité et ma passion pour le développement web, tout en étant concis et autonome.";
